[server]
maxUploadSize = 300
maxMessageSize = 300
enableXsrfProtection = false
enableCORS = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
magicEnabled = true
fastReruns = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[global]
developmentMode = false

